#!/usr/bin/env ruby
# frozen_string_literal: true

Signal.trap('INT') { exit 2 }

require_relative '../lib/tapy'

begin
  Dry::CLI.new(Tapy::CLI).call
rescue Tapy::Recipe::InstallError => e
  error_name = e.class.name.split('::').last
  abort("[#{error_name}] #{e.message}")
end
