#!/usr/bin/env ruby
# frozen_string_literal: true

Signal.trap('INT') { exit 2 }

require_relative '../lib/tapy'

begin
  Dry::CLI.new(Tapy::CLI).call
rescue Tapy::Error, Tapy::UninstallError => e
  Tapy.events.publish('tapy.error', error: e)
  exit(false)
end
